language: java
jdk:
  - oraclejdk8
install:
  - sudo apt-get update -qq
  - curl -O https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt
  - chmod +x sbt
  - sudo mv -f sbt /usr/local/bin/
script: sbt compile